### PR TITLE
Fix compilation error introduced in commit 6406d8e

### PR DESCRIPTION
**Pull request by eikemeier**

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Thanks @eikemeier

**Comment by eikemeier** [comment]
Thanks @bpoplauschi for the quick response

**Comment by mythodeia** [comment]
apparently this commit breaks the prefetcher 
check #1366
